jobs:
- name: alertmanager
  templates:
  - name: alertmanager
    release: prometheus
  instances: 1
  disk_pool: prometheus_small
  resource_pool: small_z1
  networks:
  - name: prometheus1
  properties:
    alertmanager:
      route:
        receiver: default-receiver
      receivers:
      - name: default-receiver

- name: prometheus
  templates:
  - name: prometheus
    release: prometheus
  - name: pushgateway
    release: prometheus
  - name: bosh_exporter
    release: prometheus
  - name: firehose_exporter
    release: prometheus
  - name: kube_state_metrics_exporter
    release: prometheus
  - name: bosh_alerts
    release: prometheus
  - name: cloudfoundry_alerts
    release: prometheus
  - name: prometheus_alerts
    release: prometheus
  instances: 1
  disk_pool: prometheus_large
  resource_pool: small_z1
  networks:
  - name: prometheus1
  properties:
    prometheus:
      rule_files:
      - /var/vcap/packages/bosh_alerts/*.alerts
      - /var/vcap/packages/cloudfoundry_alerts/*.alerts
      - /var/vcap/packages/kubernetes_alerts/*.alerts
      - /var/vcap/packages/prometheus_alerts/*.alerts
      scrape_configs:
      - job_name: prometheus
        static_configs:
        - targets:
          - localhost:9090
      - job_name: pushgateway
        static_configs:
        - targets:
          - localhost:9091
      - job_name: bosh
        scrape_interval: 1m
        scrape_timeout: 1m
        static_configs:
        - targets:
          - localhost:9190
      - job_name: firehose
        static_configs:
        - targets:
          - localhost:9186
      - job_name: kube_state_metrics_exporter
        static_configs:
        - targets:
          - localhost:9188
      - job_name: node
        file_sd_configs:
        - files:
          - /var/vcap/store/bosh_exporter/bosh_target_groups.json
        relabel_configs:
        - source_labels: [__meta_bosh_job_process_name]
          regex: node_exporter
          action: keep
        - source_labels: [__address__]
          regex: "(.*)"
          target_label: __address__
          replacement: "${1}:9100"

- name: grafana
  templates:
  - name: grafana
    release: prometheus
  - name: bosh_dashboards
    release: prometheus
  - name: cloudfoundry_dashboards
    release: prometheus
  - name: kubernetes_dashboards
    release: prometheus
  - name: system_dashboards
    release: prometheus
  - name: prometheus_dashboards
    release: prometheus
  instances: 1
  disk_pool: prometheus_small
  resource_pool: small_z1
  networks:
  - name: prometheus1
  properties:
    grafana:
      auth:
        generic_oauth:
          enabled: true
          allow_sign_up: true
          scopes: openid,metrics.read
      dashboards:
        json:
          enabled: true
      prometheus:
        dashboard_files:
        - /var/vcap/packages/bosh_dashboards/*.json
        - /var/vcap/packages/system_dashboards/*.json
        - /var/vcap/packages/cloudfoundry_dashboards/*.json
        - /var/vcap/packages/kubernetes_dashboards/*.json
        - /var/vcap/packages/prometheus_dashboards/*.json

- name: nginx
  templates:
  - name: nginx
    release: prometheus
  instances: 1
  disk_pool: prometheus_small
  resource_pool: small_z1_public
  networks:
  - name: prometheus1
  properties:
    nginx:
      prometheus:
        http_port: 80
        server_name: (( param "specify prometheus server name" ))
      alertmanager:
        http_port: 80
        server_name: (( param "specify alertmanager server name" ))
      grafana:
        http_port: 80
        server_name: (( param "specify grafana server name" ))

networks: (( param "please set networks" ))
